from typing import Any

import yaml
from fishpy.geometry import Point2D

CONFIGURATION_FILE = 'VerletIntegration/configurations/net_high.yml'
with open(CONFIGURATION_FILE, 'r') as config_file:
    CONFIG = yaml.safe_load(config_file)
    CONSTANTS: dict[str, Any] = CONFIG['constants']


WINDOW_SIZE = Point2D(**CONSTANTS['WINDOW_SIZE'])
FPS = CONSTANTS.get('FPS', 120)
SQUISH_ITERATIONS = CONSTANTS.get('SQUISH_ITERATIONS', 2)

BOUNCE_COEF = CONSTANTS.get('BOUNCE_COEF', 0.8)
FRICTION_COEF = CONSTANTS.get('FRICTION_COEF', 0.999)
FLOOR_FRICTION_ENABLED = CONSTANTS.get('FLOOR_FRICTION_ENABLED', True)
FLOOR_FRICTION_EXP = CONSTANTS.get('FLOOR_FRICTION_EXP', 50)
GRAVITY = CONSTANTS.get('GRAVITY', 0.5)
VISIBLE_POINTS = CONSTANTS.get('VISIBLE_POINTS', False)
DEFAULT_POINT_RADIUS = CONSTANTS.get('DEFAULT_POINT_RADIUS', 3)
BOUNDED_WALLS = CONSTANTS.get('BOUNDED_WALLS', True)
